version: '3.8'

services:
  ceragen:
    image: postgres:15
    container_name: ceragen-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: secoedV3_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "80:80"
    depends_on:
      - ceragen

  dawa-ceragen:
    container_name: dawa-project
    build:
      context: ./ws_ceragen
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ws_ceragen/src/utils/general/LOGS:/app/ws_ceragen/src/utils/general/LOGS
    environment:
      DATABASE_HOST: ceragen
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 12345
      DATABASE_NAME: secoedV3_db
      PORT: 5000
    depends_on:
      ceragen:
        condition: service_healthy
    command: ["python3", "app.py"]

  ceragen-frontend:
    build:
      context: ../../FRONTEND
      dockerfile: Dockerfile
    container_name: ceragen-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - dawa-ceragen
